<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Classification extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Classification_model');
    // if (!$this->session->userdata('isUserLoggedIn')) {
    //   redirect('Auth/login');
    // }
 } 
 /*
* Listing of classification
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['classification'] = $this->Classification_model->get_all_classification();
      $data['_view'] = 'classification/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Classification Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new classification
  */
 function add()
 {  
try{
      $params = array(
       'Classification_Name'=> $this->input->post('Classification_Name'),
       'Classification_Code'=> $this->input->post('Classification_Code'),
       'Description'=> $this->input->post('Description'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $C_ID= $this->Classification_model->add_classification($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('classification/index');
        }
        else
        { 
           $data['_view'] = 'classification/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Classification Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a classification
 */
 public function edit($C_ID)
 {   
  try{
   $data['classification'] = $this->Classification_model->get_classification($C_ID);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['classification']['C_ID']))
      {
        $params = array(
           'Classification_Name'=> $this->input->post('Classification_Name'),
           'Classification_Code'=> $this->input->post('Classification_Code'),
           'Description'=> $this->input->post('Description'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Classification_model->update_classification($C_ID,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('classification/index');
           }
           else
          {
              $data['_view'] = 'classification/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The classification you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Classification Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting classification
  */
  function remove($C_ID)
   {
    try{
      $classification = $this->Classification_model->get_classification($C_ID);
  // check if the classification exists before trying to delete it
       if(isset($classification['C_ID']))
       {
         $this->Classification_model->delete_classification($C_ID);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('classification/index');
       }
       else
       show_error('The classification you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Classification Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a classification
 */
 public function view_more($C_ID)
 {   
try{
   $data['classification'] = $this->Classification_model->get_classification($C_ID);
     if(isset($data['classification']['C_ID']))
      {
              $data['_view'] = 'classification/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The classification you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Classification Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of classification
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['classification'] = $this->Classification_model->get_all_classification_by_cat($column_name,$value_id);
      $data['_view'] = 'classification/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- classification
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Classification_model->update_classification($id,$params);
   $data['noof_page'] = 0;
  $data['classification'] = $this->Classification_model->get_all_classification();
  $this->load->view('classification/index',$data);
}
 }
