<?php
/* 
 * Generated by Manuigniter v2.0 
 *  www.manuigniter.com  
 
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        // if (!$this->session->userdata('isUserLoggedIn')) {
        //     redirect('Auth/login');
        // }
        
    }

    function index()
    {
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
        // $this->load->view('layouts/public', $data);
    }
}
