<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Sub_classification extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Sub_classification_model');
    if (!$this->session->userdata('isUserLoggedIn')) {
      redirect('Auth/login');
    }
 }

  function _auto_gen_code()
  {
    $max_id = $this->get_max();
    // $fnam=$this->get_code($max_id);
    $num = $max_id + 1;
    return sprintf("%'.03d\n", $num);
  }

  function get_code($max_id)
  {
    $max_id = $this->get_max($max_id);
    $query = $this->get_where('SC_ID', $max_id);
    foreach ($query->result() as $row) {
      $Code = $row->Code;
    }
    // echo $Code;
    return $Code;
  }


  function get_max()
  {
    $this->load->model('Sub_Classification_model');
    $max_id = $this->Sub_Classification_model->get_max();
    return $max_id;
  }
  function get_where($id)
  {
    $this->load->model('Sub_Classification_model');
    $query = $this->Sub_Classification_model->get_where($id);
    return $query;
  }
  function get_where_custom($col, $value)
  {
    $this->load->model('Sub_Classification_model');
    $query = $this->Sub_Classification_model->get_where_custom($col, $value);
    return $query;
  }
 /*
* Listing of sub_classification
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['sub_classification'] = $this->Sub_classification_model->get_all_with_asso_sub_classification();
      $data['_view'] = 'sub_classification/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Sub_classification Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new sub_classification
  */
 function add()
 {  
try{
      $params = array(
       'Sub_Classification_Name'=> $this->input->post('Sub_Classification_Name'),
       'Sub_Classification_Code'=> $this->_auto_gen_code(),
       'Classification'=> $this->input->post('Classification'),
       'Description'=> $this->input->post('Description'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $SC_ID= $this->Sub_classification_model->add_sub_classification($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('sub_classification/index');
        }
        else
        { 
         $this->load->model('Classification_model');
         $data['all_classification'] = $this->Classification_model->get_all_classification(); 
           $data['_view'] = 'sub_classification/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Sub_classification Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a sub_classification
 */
 public function edit($SC_ID)
 {   
  try{
   $data['sub_classification'] = $this->Sub_classification_model->get_sub_classification($SC_ID);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['sub_classification']['SC_ID']))
      {
        $params = array(
           'Sub_Classification_Name'=> $this->input->post('Sub_Classification_Name'),
          //  'Sub_Classification_Code'=> $this->input->post('Sub_Classification_Code'),
           'Classification'=> $this->input->post('Classification'),
           'Description'=> $this->input->post('Description'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Sub_classification_model->update_sub_classification($SC_ID,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('sub_classification/index');
           }
           else
          {
             $this->load->model('Classification_model');
             $data['all_classification'] = $this->Classification_model->get_all_classification(); 
              $data['_view'] = 'sub_classification/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The sub_classification you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Sub_classification Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting sub_classification
  */
  function remove($SC_ID)
   {
    try{
      $sub_classification = $this->Sub_classification_model->get_sub_classification($SC_ID);
  // check if the sub_classification exists before trying to delete it
       if(isset($sub_classification['SC_ID']))
       {
         $this->Sub_classification_model->delete_sub_classification($SC_ID);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('sub_classification/index');
       }
       else
       show_error('The sub_classification you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Sub_classification Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a sub_classification
 */
 public function view_more($SC_ID)
 {   
try{
   $data['sub_classification'] = $this->Sub_classification_model->get_sub_classification($SC_ID);
     if(isset($data['sub_classification']['SC_ID']))
      {
              $data['_view'] = 'sub_classification/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The sub_classification you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Sub_classification Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of sub_classification
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['sub_classification'] = $this->Sub_classification_model->get_all_with_asso_sub_classification_by_cat($column_name,$value_id);
      $data['_view'] = 'sub_classification/index';
      $this->load->view('layouts/main',$data);
}
  /*
  * get get_search_values_byclms by id
 */
 public function get_search_values_by_Classification()
 {   
     $Classification= $this->input->post('value');
        $this->load->model('Classification_model');
        $data['all_classification'] = $this->Classification_model->get_all_classification(); 
      $sub_classification = $this->Sub_classification_model->get_all_with_asso_sub_classification();
if(isset($data['all_classification']) && $data['all_classification']!=null)
                                              {
                                              foreach($data['all_classification'] as $s){ 
      echo          "<option value='".$s['Classification_Name']."'> ".$s['Classification_Name']."</option>"; 
 } 
                                              }
                                              else{
                                                        echo '<tr>No data found</tr>';
                                              }
 } 
 /*
* get search values by column- sub_classification
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Sub_classification_model->update_sub_classification($id,$params);
   $data['noof_page'] = 0;
  $data['sub_classification'] = $this->Sub_classification_model->get_all_with_asso_sub_classification();
  $this->load->view('sub_classification/index',$data);
}
 }
