<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Classification_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
  /*
        * Get classification by C_ID 
      */


  function get_table()
  {
    $table = "classification";
    return $table;
  }


  function get_max()
  {
    $table = $this->get_table();
    $this->db->select_max('C_ID');
    $query = $this->db->get($table);
    $row = $query->row();
    $id = $row->C_ID;
    return $id;
  }
  function get_where_custom($col, $value)
  {
    $table = $this->get_table();
    $this->db->where($col, $value);
    $query = $this->db->get($table);
    return $query;
  }
  function get_where($id)
  {
    $table = $this->get_table();
    $this->db->where('id', $id);
    $query = $this->db->get($table);
    return $query;
  }
      function get_classification($C_ID)
      {
        try{
           return $this->db->get_where('classification',array('C_ID'=>$C_ID))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Classification_model Model : Error in get_classification function - ' . $ex);
           }  
      }
      /*
        * Get classification by  column name
      */ 
      function get_classificationbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('classification',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Classification_model Madel : Error in get_classificationbyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All classification count 
      */ 
      function get_all_classification_count()
      {
        try{
           $this->db->from('classification');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Classification_model model : Error in get_all_classification_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join classificationcount 
      */ 
      function get_all_with_asso_classification()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Classification_model model : Error in get_all_with_asso_classification function - ' . $ex);
           }  
      }
      /*
          * Get all classification 
      */ 
      function get_all_classification($params = array())
      {
        try{
              $this->db->order_by('C_ID', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('classification')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Classification_model model : Error in get_all_classification function - ' . $ex);
           }  
      } 
      /*
         * function to add new classification 
      */
      function add_classification($params)
      {
        try{
          $this->db->insert('classification',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Classification_model model : Error in add_classification function - ' . $ex);
           }  
      }
      /* 
          * function to update classification 
      */
      function update_classification($C_ID,$params)
      {
        try{
            $this->db->where('C_ID',$C_ID);
        return $this->db->update('classification',$params);
           } catch (Exception $ex) {
             throw new Exception('Classification_model model : Error in update_classification function - ' . $ex);
           }  
       }
     /* 
          * function to delete classification 
      */
       function delete_classification($C_ID)
       {
        try{
             return $this->db->delete('classification',array('C_ID'=>$C_ID));
           } catch (Exception $ex) {
             throw new Exception('Classification_model model : Error in delete_classification function - ' . $ex);
           }  
       }
      /*
        * Get classification by  column name where not in particular id
      */ 
      function get_classificationbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('C_ID!=', $where_cond);
           return $this->db->get_where('classification',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Classification_model model : Error in get_classificationbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join classificationcount 
      */ 
      function get_all_with_asso_classification_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Classification_model model : Error in get_all_with_asso_classification_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all classification_by_cat 
      */ 
      function get_all_classification_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('C_ID', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('classification')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Classification_model model : Error in get_all_classification_by_cat function - ' . $ex);
           }  
      } 
 }
