<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Sub_classification_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get sub_classification by SC_ID 
      */ 
      function get_sub_classification($SC_ID)
      {
        try{
           return $this->db->get_where('sub_classification',array('SC_ID'=>$SC_ID))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Sub_classification_model Model : Error in get_sub_classification function - ' . $ex);
           }  
      }
      /*
        * Get sub_classification by  column name
      */ 
      function get_sub_classificationbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('sub_classification',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Sub_classification_model Madel : Error in get_sub_classificationbyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All sub_classification count 
      */ 
      function get_all_sub_classification_count()
      {
        try{
           $this->db->from('sub_classification');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Sub_classification_model model : Error in get_all_sub_classification_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join sub_classificationcount 
      */ 
      function get_all_with_asso_sub_classification()
      {
        try{
           $this->db->select('*');
           $this->db->from('sub_classification a  ' );
            $this->db->join('classification b', 'b.Classification_Name=a. Classification','left');
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Sub_classification_model model : Error in get_all_with_asso_sub_classification function - ' . $ex);
           }  
      }
      /*
          * Get all sub_classification 
      */ 
      function get_all_sub_classification($params = array())
      {
        try{
              $this->db->order_by('SC_ID', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('sub_classification')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Sub_classification_model model : Error in get_all_sub_classification function - ' . $ex);
           }  
      } 
      /*
         * function to add new sub_classification 
      */
      function add_sub_classification($params)
      {
        try{
          $this->db->insert('sub_classification',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Sub_classification_model model : Error in add_sub_classification function - ' . $ex);
           }  
      }
      /* 
          * function to update sub_classification 
      */
      function update_sub_classification($SC_ID,$params)
      {
        try{
            $this->db->where('SC_ID',$SC_ID);
        return $this->db->update('sub_classification',$params);
           } catch (Exception $ex) {
             throw new Exception('Sub_classification_model model : Error in update_sub_classification function - ' . $ex);
           }  
       }
     /* 
          * function to delete sub_classification 
      */
       function delete_sub_classification($SC_ID)
       {
        try{
             return $this->db->delete('sub_classification',array('SC_ID'=>$SC_ID));
           } catch (Exception $ex) {
             throw new Exception('Sub_classification_model model : Error in delete_sub_classification function - ' . $ex);
           }  
       }
      /*
        * Get sub_classification by  column name where not in particular id
      */ 
      function get_sub_classificationbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('SC_ID!=', $where_cond);
           return $this->db->get_where('sub_classification',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Sub_classification_model model : Error in get_sub_classificationbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join sub_classificationcount 
      */ 
      function get_all_with_asso_sub_classification_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
           $this->db->select('*');
           $this->db->from('sub_classification a  ' );
              //$this->db->where($column_name, $value_id);
            $this->db->join('classification b', 'b.Classification_Name=a. Classification','left');
              $this->db->where('a.'.$column_name, $value_id);
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Sub_classification_model model : Error in get_all_with_asso_sub_classification_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all sub_classification_by_cat 
      */ 
      function get_all_sub_classification_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('SC_ID', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('sub_classification')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Sub_classification_model model : Error in get_all_sub_classification_by_cat function - ' . $ex);
           }  
      } 
 }
