<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Sub_classification extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Sub_classification_model');
 } 
 /*
* Listing of sub_classification
 */
public function get_all_post()
{
  try{
  $data['sub_classification'] = $this->Sub_classification_model->get_all_sub_classification();
     if($data['sub_classification'] && $data['sub_classification']!=null){
       $sub_classification_ar = array();
       foreach($data['sub_classification'] as $s)
       {
       $s_ar = array();
       $s_ar['SC_ID'] = $s['SC_ID'];
       $s_ar['Sub_Classification_Name'] = $s['Sub_Classification_Name'];
       $s_ar['Sub_Classification_Code'] = $s['Sub_Classification_Code'];
       $s_ar['Classification'] = $s['Classification'];
       $s_ar['Description'] = $s['Description'];
       $sub_classification_ar[] = $s_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $sub_classification_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Sub_classification controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new sub_classification
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'Sub_Classification_Name'=> $this->input->post('Sub_Classification_Name'),
       'Sub_Classification_Code'=> $this->input->post('Sub_Classification_Code'),
       'Classification'=> $this->input->post('Classification'),
       'Description'=> $this->input->post('Description'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $SC_ID= $this->Sub_classification_model->add_sub_classification($params);
   $data['sub_classification'] = $this->Sub_classification_model->get_sub_classification($SC_ID);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Sub_classification controller_name : Error in new sub_classification function - ' . $ex);
       }  
 }  
  /*
  * Editing a sub_classification
 */
  function edit_post($SC_ID)
 {   
  try{
   $data['sub_classification'] = $this->Sub_classification_model->get_sub_classification($SC_ID);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['sub_classification']['SC_ID']))
      {
        $params = array(
           'Sub_Classification_Name'=> $this->input->post('Sub_Classification_Name'),
           'Sub_Classification_Code'=> $this->input->post('Sub_Classification_Code'),
           'Classification'=> $this->input->post('Classification'),
           'Description'=> $this->input->post('Description'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Sub_classification_model->update_sub_classification($SC_ID,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $SC_ID
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $SC_ID
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Sub_classification controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting sub_classification
  */
  function remove_post($SC_ID)
   {
  try{
      $sub_classification = $this->Sub_classification_model->get_sub_classification($SC_ID);
  // check if the sub_classification exists before trying to delete it
       if(isset($sub_classification['SC_ID']))
       {
         $this->Sub_classification_model->delete_sub_classification($SC_ID);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $SC_ID
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $SC_ID
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Sub_classification controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
